package Vista;
import Formato.*;

/**
 *
 * @author USUARIO
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuIngresos = new javax.swing.JMenu();
        mitemRegistrarProducto = new javax.swing.JMenuItem();
        mitemRegistrarMaterial = new javax.swing.JMenuItem();
        mitemRegistrarColor = new javax.swing.JMenuItem();
        mitemRegistrarCategoria = new javax.swing.JMenuItem();
        menuInventario = new javax.swing.JMenu();
        mitemConsultarStock = new javax.swing.JMenuItem();
        menuMantenimiento = new javax.swing.JMenu();
        mitemProducto = new javax.swing.JMenuItem();
        mitemCategoria = new javax.swing.JMenuItem();
        mitemColor = new javax.swing.JMenuItem();
        mitemMaterial = new javax.swing.JMenuItem();
        menuSalidas = new javax.swing.JMenu();
        mitemVentas = new javax.swing.JMenuItem();
        mitemPedidos = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenu();
        mitemRegistrarClientes = new javax.swing.JMenuItem();
        mitemClientes = new javax.swing.JMenuItem();
        menuEmpleados = new javax.swing.JMenu();
        mitemRegistrarEmpleados = new javax.swing.JMenuItem();
        mitemEmpleados = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setForeground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        jPanel1.add(escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 580));

        menuIngresos.setText("Ingresos");

        mitemRegistrarProducto.setText("Registrar producto");
        menuIngresos.add(mitemRegistrarProducto);

        mitemRegistrarMaterial.setText("Registrar material");
        menuIngresos.add(mitemRegistrarMaterial);

        mitemRegistrarColor.setText("Registrar color");
        menuIngresos.add(mitemRegistrarColor);

        mitemRegistrarCategoria.setText("Registrar categoria");
        menuIngresos.add(mitemRegistrarCategoria);

        jMenuBar1.add(menuIngresos);

        menuInventario.setText("Inventario");

        mitemConsultarStock.setText("Consultar stock");
        menuInventario.add(mitemConsultarStock);

        jMenuBar1.add(menuInventario);

        menuMantenimiento.setText("Mantenimiento");

        mitemProducto.setText("Producto");
        menuMantenimiento.add(mitemProducto);

        mitemCategoria.setText("Categoria");
        menuMantenimiento.add(mitemCategoria);

        mitemColor.setText("Color");
        menuMantenimiento.add(mitemColor);

        mitemMaterial.setText("Material");
        menuMantenimiento.add(mitemMaterial);

        jMenuBar1.add(menuMantenimiento);

        menuSalidas.setText("Salidas");

        mitemVentas.setText("Ventas");
        menuSalidas.add(mitemVentas);

        mitemPedidos.setText("Pedidos");
        menuSalidas.add(mitemPedidos);

        jMenuBar1.add(menuSalidas);

        menuClientes.setText("Clientes");

        mitemRegistrarClientes.setText("Registrar clientes");
        menuClientes.add(mitemRegistrarClientes);

        mitemClientes.setText("Clientes");
        menuClientes.add(mitemClientes);

        jMenuBar1.add(menuClientes);

        menuEmpleados.setText("Empleados");

        mitemRegistrarEmpleados.setText("Registrar empleados");
        menuEmpleados.add(mitemRegistrarEmpleados);

        mitemEmpleados.setText("Empleados");
        menuEmpleados.add(mitemEmpleados);

        jMenuBar1.add(menuEmpleados);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JMenu menuClientes;
    public javax.swing.JMenu menuEmpleados;
    public javax.swing.JMenu menuIngresos;
    public javax.swing.JMenu menuInventario;
    public javax.swing.JMenu menuMantenimiento;
    public javax.swing.JMenu menuSalidas;
    public javax.swing.JMenuItem mitemCategoria;
    public javax.swing.JMenuItem mitemClientes;
    public javax.swing.JMenuItem mitemColor;
    public javax.swing.JMenuItem mitemConsultarStock;
    public javax.swing.JMenuItem mitemEmpleados;
    public javax.swing.JMenuItem mitemMaterial;
    public javax.swing.JMenuItem mitemPedidos;
    public javax.swing.JMenuItem mitemProducto;
    public javax.swing.JMenuItem mitemRegistrarCategoria;
    public javax.swing.JMenuItem mitemRegistrarClientes;
    public javax.swing.JMenuItem mitemRegistrarColor;
    public javax.swing.JMenuItem mitemRegistrarEmpleados;
    public javax.swing.JMenuItem mitemRegistrarMaterial;
    public javax.swing.JMenuItem mitemRegistrarProducto;
    public javax.swing.JMenuItem mitemVentas;
    // End of variables declaration//GEN-END:variables
}
